lib/puppet/provider/package/dnfmodule.rb, lib/puppet/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
Fedora 41 introduced dnf5 which has deprecated the use of the flags `-d` and `-e`. This change removes the options.
Credit to @larhauga in https://github.com/puppetlabs/puppet/pull/9536
Closes #19
=> Add fix for package running dnf5 on fedora

install.rb
gzip(1) stores a timestamp in headers unless told not to do so: https://wiki.debian.org/ReproducibleBuilds/TimestampsInGzipHeaders
=> Make compressed man pages reproducible

spec/shared_examples/rhel_package_provider.rb, spec/unit/provider/package/dnfmodule_spec.rb
In commit 26d3405df7f35497ec07942c44c292bb25d60210 / PR #20 the yum/dnf provider options were updated to be dnf 5 compatible, but the unit tests were not updated at that time. This updates those tests.
=> Fix unit tests for yum/dnf provider option change

lib/puppet/util.rb
When attempting to close files, the /proc/self loop was trying to close a file being converted to an integer which was causing issues on Fedora 42, this resolved the problem.
Also see https://github.com/puppetlabs/puppet/pull/9552
=> Update util.rb to fix closing of file.

lib/puppet/util.rb, spec/unit/util_spec.rb
This starts with reverting #39 because [it's broken](https://github.com/OpenVoxProject/puppet/pull/39#issuecomment-2840341655) and caused a regression. Then   I've taken my commits from https://github.com/puppetlabs/puppet/pull/9546.
Ruby 3.4 started error checking directory access and starts to raise Errno::EBADF.
This particular loop iterates on all open file descriptors and one is the directory listing from Dir.foreach.
In the past this could have led to leaked file descriptors, but it's unlikely since it's likely the last opened file descriptor and have the highest number.
Link: https://github.com/ruby/ruby/commit/f2919bd11c570fc5f5440d1f101be38f61e3d16b
Link: https://bugzilla.redhat.com/show_bug.cgi?id=2349352
=> Avoid closing directory we're iterating

lib/puppet/provider/package/tdnf.rb, lib/puppet/type/package.rb, references/type.md, references/types/package.md
This patch fixes a typo (letter 'e' missing) and updates the indentation of a code example from two to four spaces.  This ensures the example is formatted as code in the generated markdown version.
=> Fix a typo and some formatting in the type and provider docs

spec/fixtures/ssl/generate_fixtures.rb, spec/fixtures/ssl/request.pem, spec/fixtures/ssl/tampered-csr.pem, spec/lib/puppet/test_ca.rb, spec/lib/puppet_spec/ssl.rb, spec/unit/ssl/certificate_request_spec.rb
The only valid CSR version is version 1, which is encoded with "csr.version = 0". Versions of OpenSSL prior to 3.4 would allow other versions to be set / versions to be unset but OpenSSL 3.4 is strict about only allowing version 1.
This change updates the unit tests and test fixtures to all specify or contain version 1 CSRs.
=> Fix unit test CSR versions for OpenSSL 3.4 change

lib/puppet/module_tool.rb
When removing the ContentsDescription class I forgot the require statement.
Fixes: 13cd2f5cfebbf18bb6da4dbdd36dcfff5ea49dac ("Remove unused ContentsDescription class")
=> Remove require for module_tool/contents_description

lib/puppet/provider/package/yum.rb, spec/shared_examples/rhel_package_provider.rb
From the dnf4 [manpage](https://www.man7.org/linux/man-pages/man8/dnf4.8.html):
```
Remove Command
Command: remove
Aliases: rm
Aliases for explicit NEVRA matching: remove-n, remove-na, remove-nevra
Deprecated aliases: erase, erase-n, erase-na, erase-nevra
```
Resulting in this error on fedora 42, which has dnf5:
```
Error: Execution of '/usr/sbin/dnf -y erase pipewire-libs' returned 2: Unknown argument "erase" for command "dnf5". Add "--help" for more information about the arguments.
It could be a command provided by a plugin, try: dnf5 install 'dnf5-command(erase)'
```
I tested it by replacing `erase` with `remove` in `/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/package/yum.rb` and the package was properly removed.
This is analogous to PR #28
=> Replace erase with remove, since it's no longer supported with dnf5

Gemfile
These entries were copied to the gemspec but they should have been moved instead.
Fixes: 7e4903ddb028 ("adding new Gemfile entrties into the puppet.gemspec file as runtime depndencies")
=> Remove duplicate entries from Gemfile

lib/puppet/node/facts.rb, lib/puppet/node/server_facts.rb, spec/unit/node/facts_spec.rb
As specified in OpenVoxProject/planning#39, the agent will now make its implementation flavor known to the compiler through a built-in fact, as will the server (through a server fact).
=> Add 'implementation' fact to agent and server.

.rubocop.yml
when they are loaded via `require`, they will log a bunch of warnings into CI:
```
rubocop-i18n extension supports plugin, specify `plugins: rubocop-i18n` instead of `require: rubocop-i18n` in /home/runner/work/puppet/puppet/.rubocop.yml.
rubocop-performance extension supports plugin, specify `plugins: rubocop-performance` instead of `require: rubocop-performance` in /home/runner/work/puppet/puppet/.rubocop.yml.
rubocop-rake extension supports plugin, specify `plugins: rubocop-rake` instead of `require: rubocop-rake` in /home/runner/work/puppet/puppet/.rubocop.yml.
rubocop-rspec extension supports plugin, specify `plugins: rubocop-rspec` instead of `require: rubocop-rspec` in /home/runner/work/puppet/puppet/.rubocop.yml.
```
=> rubocop: load plugins as actual plugins

.github/release.yml
We use the same config in our other Vox Pupuli projects. For example https://github.com/voxpupuli/modulesync_config/blob/master/.github/release.yml
=> Update release default lables

.github/workflows/release.yaml, Gemfile, Rakefile, puppet.gemspec
In the Vox Pupuli tradition, use labels in GitHub issues to generate a human readable changelog when we release a new version of the code.
Also create a release page, and attach the gem to it.
I really like the way puppetlabs ci has a release preparation action that set version and update the changelog to allow a review. This is more work that what I can afford ATM, but we can go in that direction in the future.
=> Generate human-readable ChangeLog

puppet.gemspec
This reverts commit bf87d142f2643e05c4c5564ad6eb732e8331cef7.
When building a gem, this file is processed by the gem(1) command and
the installed file is the result of a bunch of substitutions.
However, when building AIO packages, the file is copied as is, and
a relative path will not work properly.  This result in a flood of
warnings about invalid gemspec:
```
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/3.2.0/specifications/puppet-8.19.0.gemspec]: cannot load such file -- /opt/puppetlabs/puppet/lib/ruby/gems/3.2.0/specifications/lib/puppet/version
```
=> Fix invalid gemspec in AIO package

.github/workflows/release.yaml
While here, adjust the GitHub registry URL to test the chages in #86.
=> Borrow the release workflow from the main branch

.rubocop.yml, lib/puppet/feature/base.rb, lib/puppet/functions/defined.rb, lib/puppet/parameter.rb, lib/puppet/property.rb, lib/puppet/property/keyvalue.rb, lib/puppet/property/list.rb, lib/puppet/provider.rb, lib/puppet/type/file/group.rb, lib/puppet/type/file/mode.rb, lib/puppet/type/file/owner.rb, lib/puppet/type/group.rb, lib/puppet/type/package.rb
RuboCop 1.76 changed the name of this cop and it needs to be reflected.
=> Rename Naming/PredicateName to PreficatePrefix

Gemfile, puppet.gemspec
racc came as a default gem in Ruby < 3.3 but after that it became a bundled gem. This means it must be listed as a proper dependency.
=> Add racc gem dependency

lib/puppet/util.rb, spec/unit/util/logging_spec.rb
Ruby 3.4 changed the stack frame formatting and that meant it no longer recognized the Puppet stack frames. This updates the regex for the new format.
=> Reflect Ruby 3.4 stack trace changes

puppet.gemspec
With Ruby 3.4 the base64 gem changed from a default gem to a bundled gem. This means it needs to be specified as a dependency.
=> Add base64 and syslog as gem dependencies for Ruby 3.4

lib/puppet/node/server_facts.rb
This avoids the spurious warning when copying facts and server_facts to top level. (which we NEED to deprecate.)
Fixes OpenVoxProject/openvox-agent#66
(cherry picked from commit 027841871ae4ff0b750da2f4e1489a95f2551cc4)
=> Switch to $serverimplementation

Gemfile, Rakefile
That allows us to skip the installation. It also has dependencies that are incompatible with JRuby.
(cherry picked from commit 97e13bb1ae441ef9a18440bda84263b25e3d54f4)
=> GCG: move it to dedicated gem group

.github/workflows/release.yaml
The gem artifact isn't in the pkg/ subfolder, it's in the root dir.
=> Release: Fix path to gem

Gemfile, lib/puppet/face/facts.rb, puppet.gemspec, spec/unit/application/facts_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
https://github.com/OpenVoxProject/puppet/pull/125
=> rspec-mocks: Pin to < 3.13.3

lib/puppet/face/facts.rb, puppet.gemspec, spec/unit/application/facts_spec.rb, spec/unit/provider/package/puppetserver_gem_spec.rb
The JSON gem has historically included newlines when pretty printing empty arrays or hashes. This changed with ruby/json@b2c4480 in JSON 2.8.0.
In order to maintain consistent behavior for our users, this commit special cases empty array and hash facts and adds a new test for empty hashes.
=> Maintain consistent JSON formatting / Add space to URI error

spec/unit/pops/types/string_converter_spec.rb
The version of JRuby we are using do support the `%a` format.  This
result in a bunch of extra failures on JRuby because the tests are
expected to fail but are actually passing.
Remove the pending and make the test ensure the result is the expected
on on JRuby.
=> Remove `pending` when testing StringConverter with JRuby

install.rb
This drops the use of Facter in `install.rb`. It drops Solaris support and then rewrites the Windows detect to use `RUBY_PLATFORM` instead. It then also drops the prereq checking since that doesn't really serve a purpose anymore.
=> Remove facter from install.rb

.github/workflows/acceptance.yaml
Debian 10 was eol last year. Packages have now been dropped from the main deb.debian.org mirrors and are now available only from archive.debian.org, so the images no longer work correctly.
=> (maint) Drop debian-10 from testing matrix

.github/workflows/tests.yaml, spec/unit/file_system/path_pattern_spec.rb, spec/unit/functions/break_spec.rb, spec/unit/functions/next_spec.rb, spec/unit/functions/return_spec.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/parser/compiler_spec.rb, spec/unit/task_spec.rb, spec/unit/util/json_spec.rb
At a previous step, we already run `bundle env`, we don't need to duplicate the information.
=> CI: Dont output debug infos twice

.github/workflows/tests.yaml, spec/unit/file_system/path_pattern_spec.rb, spec/unit/functions/break_spec.rb, spec/unit/functions/next_spec.rb, spec/unit/functions/return_spec.rb, spec/unit/http/service/compiler_spec.rb, spec/unit/parser/compiler_spec.rb, spec/unit/task_spec.rb, spec/unit/util/json_spec.rb
In reality, we require Ruby 3.2. On Linux we also test on Ruby 3.2+. This will save us some CI resources.
=> CI: Drop Windows Ruby 3.1 testing

lib/puppet/util/run_mode.rb
Systemd will export the environment variable RUNTIME_DIRECTORY when running a deamon. This avoids the need for shipping a tmpfiles.d entry to create the run directory.
Link: https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory=
This relates to https://github.com/OpenVoxProject/planning/issues/69. I don't quite know this will interact because I don't know if this method will also be read by the clojure code.
=> Respect systemd's RUNTIME_DIRECTORY environment variable

lib/puppet/face/config.rb, spec/unit/face/config_spec.rb
Prior to this, if OpenVox was installed via gem and the first command you run is setting configuration then it fails because `confdir` doesn't exist yet. This corrects that.
It doesn't bother setting permissions because future runs will correct the permissions.
=> Ensure confdir exists

lib/puppet/provider/service/windows.rb
Windows service accounts are *case preserving* but not *case sensitive*.
Before this change, Windows service logon account names were compared directly as case sensitive. When there was a case mismatch, it was treated as a change to the account and the service was restarted. This now normalizes case before comparing, reducing spurious restarts.
=> treat windows service accounts as case insensitive

lib/puppet/version.rb
This was inadvertently not bumped in the last release. We'll bump it again before the next one, but adding this for some amount of correctness.
=> Fix version

.rubocop_todo.yml, Gemfile
Because this repo now has many thousands more commits in it, the upstream version of the changelog generator takes a huge amount of time (6+ hours). This uses our branch which makes it far more efficient.
=> Use our branch of changelog generator

.github/workflows/acceptance.yml
These parameters are now centralized as a set of per project defaults in
beaker_acceptance.yml and no longer need to be explicitly passed in.
Also, switches from identifying on 'project-name' to 'suite-name', since
there may be multiple test suites per repository.
---
Run both openvox and openvox-agent acceptance in a matrix
now that we have both acceptance and packaging/acceptance suites (the
later being the openvox-agent acceptance suite).
Requires openvoxproject/shared-actions#44
=> Update acceptance workflow for changed beaker acceptance

.github/workflows/build.yml
When we're just testing things, we often don't need to upload things to S3 and can just download the artifacts directly from the job. This lets us disable uploading to S3 so we don't fill it with too much garbage.
=> Add switch for uploading to S3

lib/puppet/provider/package/yum.rb, spec/shared_examples/rhel_package_provider.rb
This solves the observed issue (on at least RHEL8)  if repo_gpgcheck=1 AND baseurl is changed (by a yumrepo resources for example) AND no other puppet package with dnf -y (assumeyes) has been run then dnf asks to re-import already imported keys (the key needs to be imported into dnf's databases, which is separate from rpm database and it is a new database per baseurl https://bugzilla.redhat.com/show_bug.cgi?id=1768206). If puppet then runs `dnf check-update` because of a package has `ensure => latest` then it fails with: `Warning: Puppet::Type::Package::ProviderDnf: Could not check for updates, '/bin/dnf check-update' exited with 1`
Add assumeyes to check-update, this also makes it more consistent with the other dnf commands in yum.rb which also use "-y"
=> `yum` package provider: add `assumeyes` to `yum check-update`
